version: '3.7'
services:
  redis:
    container_name: redis_container
    image: redis
    expose:
      - 6379
  db:
    container_name: mysql_container
    build: ./db
    expose: 
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
  server:
    container_name: ws_container
    build: ./websocket_server
    # expose:
    #   - 3001
    ports:
      - 8080:8080
    depends_on:
      - redis
      - db
    environment:
      - DB_HOST=db
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - PYTHON_PATH=/usr/bin/python
  # client:
  #   container_name: client_container
  #   environment:
  #     - REACT_APP_SOCKET_URL=ws://server:3001
  #   build: ./client2
  #   # expose:
  #   #   - 3000
  #   ports: 
  #     - 3000:3000
  #   depends_on:
  #     - server
# TODO: Fix client, for some reason it does not connect to the server???