version: '3.7'
services:
  redis:
    container_name: redis_container
    image: redis
    expose:
      - 6379
    # ports: 
    #   - 6379:6379
  server:
    container_name: ws_container
    build: ./websocket_server
    # expose:
    #   - 3001
    ports:
      - 8080:8080
    depends_on:
      - redis
  # client:
  #   container_name: client_container
  #   environment:
  #     - REACT_APP_SOCKET_URL=ws://server:3001
  #   build: ./client2
  #   # expose:
  #   #   - 3000
  #   ports: 
  #     - 3000:3000
  #   depends_on:
  #     - server
# TODO: Fix client, for some reason it does not connect to the server???