version: '3.7'
services:
  redis:
    container_name: redis_container
    image: redis
    expose:
      - 6379
  db:
    container_name: mysql_container
    build: ./db
    image: c09db:latest
    expose: 
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
  server:
    container_name: ws_container
    build: ./websocket_server
    image: c09app:latest

    ports:
      - 8080:8080
    depends_on:
      - redis
      - db
    environment:
      - DB_HOST=db
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - PYTHON_PATH=/usr/bin/python

