DROP DATABASE IF EXISTS USERS;
CREATE DATABASE USERS;
USE USERS;
CREATE TABLE ROLES(
  ID INT NOT NULL AUTO_INCREMENT,
  Role VARCHAR(255) NOT NULL, 
  PRIMARY KEY(id)
);

INSERT INTO ROLES(Role) VALUE("STUDENT");
INSERT INTO ROLES(Role) VALUE("TEACHING ASSISTANT");
INSERT INTO ROLES(Role) VALUE("INSTRUCTOR");

CREATE TABLE USERS(
	ID INT NOT NULL AUTO_INCREMENT,
    RoleID INT NOT NULL,
    Username VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Salt VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(RoleID) REFERENCES ROLES(ID)
);